### PR TITLE
Repository hooks emails branches

### PR DESCRIPTION
**Pull request by falexandrou**
Hi there, I've added some extra functionality (& tests) in the gem.

Here are the things i did:
- Added email lookup & listing functionality for the user
- Added hooks CRUD functionality
- Added branches listing & lookup functionality
- Updated the documentation urls
- Added `user_agent`  configurable attribute and also `access_token`, `client_id`, `client_secret` in order for us to enable `OAuth2` functionality as I asked [here](https://github.com/hirakiuc/tinybucket/issues/93)
- Updated the documentation urls because Atlassian moved the wiki to the domain `developer.atlassian.com`

Any thoughts, comments etc are more than welcome.

Cheers,
Fotis

### CODE REVIEW

**Comment by falexandrou** [comment]
Sorry for all the spam. I'm battle testing this gem a bit and I'm fixing bugs. On [this commit](https://github.com/hirakiuc/tinybucket/pull/94/commits/853d9a29d010770fbf129b8f79de0541be03292d) I switched requests to `:json` because BitBucket API supports it better. I've found cases where HTML is returned as error list and even worse, there was a case where bitbucket threw a `500` error `JSON object couldn't be decoded`, so it was the best solution

**Comment by hirakiuc** [comment]
Thank you for your contribution. 😄     

After you fixes failure of test case, I'll try to check this. 👍 

---

And I have a comment about **The scope of a Pull request**.

Many contributions are welcome 🎉 
But, this pull request includes some features and improvements.  😢  

I believe that pull request should focus on just one feature or enhancement, bug fix if the pull request should be reviewed by someone, to keep the quality of the code. 🤔   

Of cause, there is some case that a pull request should include some features and improvements for some reason. 😅 

Do you think about this❓

**Comment by falexandrou** [comment]
Hi @hirakiuc 

There isn't any failing test, just a few offenses by rubocup. I will try to sort them out. I will also try to rebase this big pull request into a few smaller ones, which would be far easier to review. Thing is I'm battle-testing this gem so I was in a rush. Will send you a few new PRs anytime soon

**Comment by hirakiuc** [comment]
@falexandrou  Thanks for understanding my thought. 😄 

O.K.  I'll check your pull requests when ready to be reviewed. 👍

**Comment by hirakiuc** [comment]
@falexandrou I'll close your PR because your PR(s) keeps without no progress in about two months. 😭 

And I notice you that I'll implement some features includes in this PR because a user requests in #97.  

I'm sorry if you have still the passion for working with this gem. 🙇 

Of cause, I'll welcome your great PRs, anytime. 😄

**Comment by falexandrou** [comment]
@hirakiuc Hey there, I'm sorry I've haven't found the time yet to work on this. 

Since my code is close to being shippable, I'll create the PRs now

**Comment by falexandrou** [comment]
Hi again @hirakiuc, I've submitted a few PRs, 2 of them require a few more tests which I'll probably do on monday. You can check the rest of them :)

**Pull request closed without merging**
