### PR TITLE
Merge pullrequest feature

### PR DESCRIPTION
**Pull request by mvlbarcelos**
Feature to merge pullrequest.

### CODE REVIEW

**Comment by hirakiuc** [comment]
Thank you for your pr !

I'll check this in this week.

**Comment by dvbeato** [comment]
+1

**Comment by hirakiuc** [comment]
Your code looks good to me !

But I try to merge my pull request with thie feature on bitbucket, Bitbucket API respond 400 Error response with `{"error": {"message": "Conflicts during merge."}}`. (My pull req on bitbucket does not have conflict issue.)

This problem looks like Bitbucket API issue...

**Comment by mvlbarcelos** [comment]
I have the same problem  and i open this issue https://bitbucket.org/site/master/issues/11895/error-api-accept-and-merge-a-pull-request .

I will contact the support.

**Comment by hirakiuc** [comment]
Thanks, @mvlbarcelos !

**Comment by mvlbarcelos** [comment]
Hi @hirakiuc follow up of a issue:


Hi Marcus,

I've talked internally to some colleagues and this looks to be a bug.

I'm escalating this for our Developer Team and we should be back to you soon.

Thank you in advance for your patience.

All the best 
Renato Rudnicki
Atlassian Support

**Comment by mvlbarcelos** [comment]
Hi @hirakiuc follow for this issue:
https://bitbucket.org/site/master/issues/11895/error-api-accept-and-merge-a-pull-request

From the development team:
This is a bug. It is not using the default commit message for the merge commit when using the API. The fix will be deployed to production by this coming Monday. A workaround is to specify a message in the request you send. The docs are correct in stating that the message field is optional, but for the time being you will need to specify one.
https://confluence.atlassian.com/bitbucket/pullrequests-resource-423626332.html#pullrequestsResource-Acceptandmergeapullrequest

**Comment by hirakiuc** [comment]
> From the development team:
> This is a bug. It is not using the default commit message for the merge commit when using the API. The fix will be deployed to production by this coming Monday. 

I see.

I'll try to test again after next Monday,  and merge this pull request if no problem occurred.

Thanks again, @mvlbarcelos !

**Comment by hirakiuc** [comment]
I try to merge my pull req on bitbucket with this feature, and merged successfully.

:+1:

**Pull request merged**
