### PR TITLE
Implemented Tags API based on the current Branches API

### PR DESCRIPTION
**Pull request by VitorHP**
So. I needed the Tags API to work for a pet project of mine, so I did it basically copying all the Branch related stuff and renaming appropriately fixing stuff when necessary.

Dont't know if that's the way you would approach that. Maybe generalizing an Entity that could be used for both tags and branches would be better since they work pretty much the same way.

### CODE REVIEW

**Comment by hirakiuc** [comment]
Sorry, I found this just now.

Thanks for your contribution 👍 

> Don't know if that's the way you would approach that. Maybe generalizing an Entity that could be used for both tags and branches would be better since they work pretty much the same way.

hmm.

Bitbucket has so many resources.
There are some resources which they look like almost the same. 
So tinybucket may be refactored/re-designed to define those resource by using inheritance 🤔 

But I already don't use Bitbucket and don't have enough time to do that, sorry 😭 

Anyway, Creating a new Model looks good for me, just now 👍

**Comment by hirakiuc** [comment]
I'll check this tomorrow in detail 🙋‍♂️

**Comment by jackwilliams04** [comment]
Can this be merged if all is ok? I would love to be able to use this new tag method for calling the BB api :)

**Comment by hirakiuc** [comment]
I'll merge this PR for now even though I have no test environment, without actual E2E test.
(I'll add some E2E test case in CI, later. 🙋🏼)

Sorry for this long delay, thanks for your patient.

**Pull request merged**
