### PR TITLE
:sparkles: Add projects api

### PR DESCRIPTION
**Pull request by hirakiuc**
Add `/2.0/teams/<owner>/projects` API

Ref: #128 

## Detail

Add projects API on team.

### New APIs

```
bucket = Tinybucket.new
team = bucket.team('my_team')

# Fetch projects
team.projects

# Fetch the project
team.project('project_key)
```

### CODE REVIEW

**Comment by hirakiuc** [comment]
This code does not work yet.

```console
D, [2017-07-02T22:04:31.221510 #99958] DEBUG -- : [api.bitbucket.org] GET /2.0/teams/altabjpworks/projects (0.792 s)
/Users/hirakiuc/repos/src/github.com/hirakiuc/tinybucket/lib/tinybucket/response/handler.rb:13:in `on_complete': GET https://api.bitbucket.org/2.0/teams/altabjpworks/projects 404 {"type": "error", "error": {"message": "Resource not found", "detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}} (Tinybucket::Error::NotFound)
        from /Users/hirakiuc/repos/src/github.com/hirakiuc/tinybucket/.bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
        from /Users/hirakiuc/repos/src/github.com/hirakiuc/tinybucket/.bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
        from /Users/hirakiuc/repos/src/github.com/hirakiuc/tinybucket/.bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
        from /Users/hirakiuc/repos/src/github.com/hirakiuc/tinybucket/.bundle/ruby/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in
```

**Comment by hirakiuc** [comment]
https://community.atlassian.com/t5/Answers-Developer-Questions/Will-it-be-possible-to-access-team-project-resources-for/qaq-p/506906

It looks like that the API is not provided yet to users... 😩

**Comment by hirakiuc** [comment]
https://community.atlassian.com/t5/Bitbucket-questions/Can-I-use-quot-GET-2-0-teams-lt-owner-gt-projects-quot-API/qaq-p/604644#M17361

**Comment by npadgen** [comment]
Suggest raising an issue at https://bitbucket.org/site/master/issues rather than relying on the community forum.

Thanks for the work you've done so far.

**Comment by hirakiuc** [comment]
Thanks for your suggestion 👍 

I'll create the issue at the https://bitbucket.org/site/master/issues if there is no answer from the community in few days.

**Comment by hirakiuc** [comment]
I created a new support request and waiting for the answer...

**Comment by hirakiuc** [comment]
I received a message from Bitbucket support team and fixed the issue! 👍 

This code works for me with this branch.

```ruby
bucket = Tinybucket.new
bucket.teams('admin').each do |team|
  p team
  team.projects.each do |project|
    p project
  end
end
```

**Comment by npadgen** [comment]
That code works for me as well!

Could you include support for finding the repos belonging to a team – /2.0/teams/{username}/repositories
https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams/%7Busername%7D/repositories

Thanks!

**Comment by hirakiuc** [comment]
Oh, Sorry. I found your comment, just now.

> Could you include support for finding the repos belonging to a team – /2.0/teams/{username}/repositories

I'll try to do that after this pull request. 😄

**Comment by npadgen** [comment]
Perfect, thanks :)

**Comment by hirakiuc** [comment]
This pull request just implements 'GET' methods only.

#131, #132 remains yet.

**Comment by hirakiuc** [comment]
LGTM 👍

**Pull request merged**
